spring:
  application:
    name: ads-kis-map-api

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/kidsmap}

server:
  port: 8080

logging:
  level:
    com.finstream: INFO
    org.apache.kafka: WARN
